#!/usr/bin/env ruby

diff = `git diff HEAD HEAD~1 --stat`
system('bundle install') if diff.include?('Gemfile')
system('./proassets') if (diff.include?('.css') || diff.include?('.js'))
if File.exists?('tmp/pids/unicorn.pid')
    unicorn_pid = File.read('tmp/pids/unicorn.pid').strip if File.exists?('tmp/pids/unicorn.pid')
    puts "Restarting Unicorn (#{unicorn_pid})"
    system("kill -9 #{unicorn_pid}")
end
system('unicorn_rails -c config/unicorn.rb -D -E production')
